version: 2
jobs:
  test:
    docker:
      - image: cimg/node:14.19.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm ci
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Send to Coveralls
          command: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
          - .

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
