version: 2
jobs:
  checkout_and_install:
    docker:
      # specify the version you desire here
      - image: node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CIRCLE_SHA1 }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Environment.CIRCLE_SHA1 }}
  test:
    docker:
      # specify the version you desire here
      - image: node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm test
      - save_cache:
          paths:
            - coverage
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
  coveralls:
    docker:
      # specify the version you desire here
      - image: node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CIRCLE_SHA1 }}
          - coverage-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm test

workflows:
  version: 2
  checkout_and_test:
    jobs:
      - checkout_and_install
      - test:
          requires:
            - checkout_and_install
      - coveralls:
          requires:
            - test
          filters:
            branches:
              only: master

# workflows:
#   version: 2
#   dev_stage_pre-prod:
#     jobs:
#       - test_dev:
#           filters:
#             branches:
#               only:
#                 - dev
#                 - /user-.*/
#       - test_stage:
#           filters:
#             branches:
#               only: stage
#       - test_pre-prod:
#           filters:
#             branches:
#               only: /pre-prod(?:-.+)?$/

  # build:
  #   docker:
  #     # specify the version you desire here
  #     - image: node:8.9.0
  #   working_directory: ~/repo
  #   branches:
  #     only:
  #       - master
  #   steps:
  #     - checkout
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #         - dependencies-{{ .Environment.CIRCLE_SHA1 }}
  #         # fallback to using the latest cache if no exact match is found
  #         - dependencies-
  #     - run: npm install
  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: dependencies-{{ .Environment.CIRCLE_SHA1 }}
  #     # run tests
  #     - run: npm test
  #     # send to coveralls
  #     - run: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  #
  # pr:
  #   docker:
  #     # specify the version you desire here
  #     - image: node:8.9.0
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #         - dependencies-{{ .Environment.CIRCLE_SHA1 }}
  #         # fallback to using the latest cache if no exact match is found
  #         - dependencies-
  #     - run: npm install
  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: dependencies-{{ .Environment.CIRCLE_SHA1 }}
  #     # run tests
  #     - run: npm test
